<?php

/* custom routes generated by CRUD */


Route::group(array('prefix' => 'admin/','namespace' => 'Admin','middleware' => 'admin','as'=>'admin.'), function () {

Route::get('kementerians', ['as'=> 'kementerians.index', 'uses' => 'KementerianController@index']);
Route::post('kementerians', ['as'=> 'kementerians.store', 'uses' => 'KementerianController@store']);
Route::get('kementerians/create', ['as'=> 'kementerians.create', 'uses' => 'KementerianController@create']);
Route::put('kementerians/{kementerians}', ['as'=> 'kementerians.update', 'uses' => 'KementerianController@update']);
Route::patch('kementerians/{kementerians}', ['as'=> 'kementerians.update', 'uses' => 'KementerianController@update']);
Route::get('kementerians/{id}/delete', ['as' => 'kementerians.delete', 'uses' => 'KementerianController@getDelete']);
Route::get('kementerians/{id}/confirm-delete', ['as' => 'kementerians.confirm-delete', 'uses' => 'KementerianController@getModalDelete']);
Route::get('kementerians/{kementerians}', ['as'=> 'kementerians.show', 'uses' => 'KementerianController@show']);
Route::get('kementerians/{kementerians}/edit', ['as'=> 'kementerians.edit', 'uses' => 'KementerianController@edit']);

});


Route::group(array('prefix' => 'admin/','namespace' => 'Admin','middleware' => 'admin','as'=>'admin.'), function () {

Route::get('banks', ['as'=> 'banks.index', 'uses' => 'BankController@index']);
Route::post('banks', ['as'=> 'banks.store', 'uses' => 'BankController@store']);
Route::get('banks/create', ['as'=> 'banks.create', 'uses' => 'BankController@create']);
Route::put('banks/{banks}', ['as'=> 'banks.update', 'uses' => 'BankController@update']);
Route::patch('banks/{banks}', ['as'=> 'banks.update', 'uses' => 'BankController@update']);
Route::get('banks/{id}/delete', ['as' => 'banks.delete', 'uses' => 'BankController@getDelete']);
Route::get('banks/{id}/confirm-delete', ['as' => 'banks.confirm-delete', 'uses' => 'BankController@getModalDelete']);
Route::get('banks/{banks}', ['as'=> 'banks.show', 'uses' => 'BankController@show']);
Route::get('banks/{banks}/edit', ['as'=> 'banks.edit', 'uses' => 'BankController@edit']);

});


Route::group(array('prefix' => 'admin/','namespace' => 'Admin','middleware' => 'admin','as'=>'admin.'), function () {

Route::get('kotas', ['as'=> 'kotas.index', 'uses' => 'KotaController@index']);
Route::post('kotas', ['as'=> 'kotas.store', 'uses' => 'KotaController@store']);
Route::get('kotas/create', ['as'=> 'kotas.create', 'uses' => 'KotaController@create']);
Route::put('kotas/{kotas}', ['as'=> 'kotas.update', 'uses' => 'KotaController@update']);
Route::patch('kotas/{kotas}', ['as'=> 'kotas.update', 'uses' => 'KotaController@update']);
Route::get('kotas/{id}/delete', ['as' => 'kotas.delete', 'uses' => 'KotaController@getDelete']);
Route::get('kotas/{id}/confirm-delete', ['as' => 'kotas.confirm-delete', 'uses' => 'KotaController@getModalDelete']);
Route::get('kotas/{kotas}', ['as'=> 'kotas.show', 'uses' => 'KotaController@show']);
Route::get('kotas/{kotas}/edit', ['as'=> 'kotas.edit', 'uses' => 'KotaController@edit']);

});


Route::group(array('prefix' => 'admin/','namespace' => 'Admin','middleware' => 'admin','as'=>'admin.'), function () {

Route::get('provinsis', ['as'=> 'provinsis.index', 'uses' => 'ProvinsiController@index']);
Route::post('provinsis', ['as'=> 'provinsis.store', 'uses' => 'ProvinsiController@store']);
Route::get('provinsis/create', ['as'=> 'provinsis.create', 'uses' => 'ProvinsiController@create']);
Route::put('provinsis/{provinsis}', ['as'=> 'provinsis.update', 'uses' => 'ProvinsiController@update']);
Route::patch('provinsis/{provinsis}', ['as'=> 'provinsis.update', 'uses' => 'ProvinsiController@update']);
Route::get('provinsis/{id}/delete', ['as' => 'provinsis.delete', 'uses' => 'ProvinsiController@getDelete']);
Route::get('provinsis/{id}/confirm-delete', ['as' => 'provinsis.confirm-delete', 'uses' => 'ProvinsiController@getModalDelete']);
Route::get('provinsis/{provinsis}', ['as'=> 'provinsis.show', 'uses' => 'ProvinsiController@show']);
Route::get('provinsis/{provinsis}/edit', ['as'=> 'provinsis.edit', 'uses' => 'ProvinsiController@edit']);

});


Route::group(array('prefix' => 'admin/','namespace' => 'Admin','middleware' => 'admin','as'=>'admin.'), function () {

Route::get('kecamatans', ['as'=> 'kecamatans.index', 'uses' => 'KecamatanController@index']);
Route::post('kecamatans', ['as'=> 'kecamatans.store', 'uses' => 'KecamatanController@store']);
Route::get('kecamatans/create', ['as'=> 'kecamatans.create', 'uses' => 'KecamatanController@create']);
Route::put('kecamatans/{kecamatans}', ['as'=> 'kecamatans.update', 'uses' => 'KecamatanController@update']);
Route::patch('kecamatans/{kecamatans}', ['as'=> 'kecamatans.update', 'uses' => 'KecamatanController@update']);
Route::get('kecamatans/{id}/delete', ['as' => 'kecamatans.delete', 'uses' => 'KecamatanController@getDelete']);
Route::get('kecamatans/{id}/confirm-delete', ['as' => 'kecamatans.confirm-delete', 'uses' => 'KecamatanController@getModalDelete']);
Route::get('kecamatans/{kecamatans}', ['as'=> 'kecamatans.show', 'uses' => 'KecamatanController@show']);
Route::get('kecamatans/{kecamatans}/edit', ['as'=> 'kecamatans.edit', 'uses' => 'KecamatanController@edit']);

});


Route::group(array('prefix' => 'admin/','namespace' => 'Admin','middleware' => 'admin','as'=>'admin.'), function () {

Route::get('kelurahans', ['as'=> 'kelurahans.index', 'uses' => 'KelurahanController@index']);
Route::post('kelurahans', ['as'=> 'kelurahans.store', 'uses' => 'KelurahanController@store']);
Route::get('kelurahans/create', ['as'=> 'kelurahans.create', 'uses' => 'KelurahanController@create']);
Route::put('kelurahans/{kelurahans}', ['as'=> 'kelurahans.update', 'uses' => 'KelurahanController@update']);
Route::patch('kelurahans/{kelurahans}', ['as'=> 'kelurahans.update', 'uses' => 'KelurahanController@update']);
Route::get('kelurahans/{id}/delete', ['as' => 'kelurahans.delete', 'uses' => 'KelurahanController@getDelete']);
Route::get('kelurahans/{id}/confirm-delete', ['as' => 'kelurahans.confirm-delete', 'uses' => 'KelurahanController@getModalDelete']);
Route::get('kelurahans/{kelurahans}', ['as'=> 'kelurahans.show', 'uses' => 'KelurahanController@show']);
Route::get('kelurahans/{kelurahans}/edit', ['as'=> 'kelurahans.edit', 'uses' => 'KelurahanController@edit']);

});


Route::group(array('prefix' => 'admin/','namespace' => 'Admin','middleware' => 'admin','as'=>'admin.'), function () {

Route::get('layanans', ['as'=> 'layanans.index', 'uses' => 'LayananController@index']);
Route::post('layanans', ['as'=> 'layanans.store', 'uses' => 'LayananController@store']);
Route::get('layanans/create', ['as'=> 'layanans.create', 'uses' => 'LayananController@create']);
Route::put('layanans/{layanans}', ['as'=> 'layanans.update', 'uses' => 'LayananController@update']);
Route::patch('layanans/{layanans}', ['as'=> 'layanans.update', 'uses' => 'LayananController@update']);
Route::get('layanans/{id}/delete', ['as' => 'layanans.delete', 'uses' => 'LayananController@getDelete']);
Route::get('layanans/{id}/confirm-delete', ['as' => 'layanans.confirm-delete', 'uses' => 'LayananController@getModalDelete']);
Route::get('layanans/{layanans}', ['as'=> 'layanans.show', 'uses' => 'LayananController@show']);
Route::get('layanans/{layanans}/edit', ['as'=> 'layanans.edit', 'uses' => 'LayananController@edit']);

});


Route::group(array('prefix' => 'admin/','namespace' => 'Admin','middleware' => 'admin','as'=>'admin.'), function () {

Route::get('payments', ['as'=> 'payments.index', 'uses' => 'PaymentController@index']);
Route::post('payments', ['as'=> 'payments.store', 'uses' => 'PaymentController@store']);
Route::get('payments/create', ['as'=> 'payments.create', 'uses' => 'PaymentController@create']);
Route::put('payments/{payments}', ['as'=> 'payments.update', 'uses' => 'PaymentController@update']);
Route::patch('payments/{payments}', ['as'=> 'payments.update', 'uses' => 'PaymentController@update']);
Route::get('payments/{id}/delete', ['as' => 'payments.delete', 'uses' => 'PaymentController@getDelete']);
Route::get('payments/{id}/confirm-delete', ['as' => 'payments.confirm-delete', 'uses' => 'PaymentController@getModalDelete']);
Route::get('payments/{payments}', ['as'=> 'payments.show', 'uses' => 'PaymentController@show']);
Route::get('payments/{payments}/edit', ['as'=> 'payments.edit', 'uses' => 'PaymentController@edit']);

});


Route::group(array('prefix' => 'admin/','namespace' => 'Admin','middleware' => 'admin','as'=>'admin.'), function () {

Route::get('jamaahs', ['as'=> 'jamaahs.index', 'uses' => 'JamaahController@index']);
Route::post('jamaahs', ['as'=> 'jamaahs.store', 'uses' => 'JamaahController@store']);
Route::get('jamaahs/create', ['as'=> 'jamaahs.create', 'uses' => 'JamaahController@create']);
Route::put('jamaahs/{jamaahs}', ['as'=> 'jamaahs.update', 'uses' => 'JamaahController@update']);
Route::patch('jamaahs/{jamaahs}', ['as'=> 'jamaahs.update', 'uses' => 'JamaahController@update']);
Route::get('jamaahs/{id}/delete', ['as' => 'jamaahs.delete', 'uses' => 'JamaahController@getDelete']);
Route::get('jamaahs/{id}/confirm-delete', ['as' => 'jamaahs.confirm-delete', 'uses' => 'JamaahController@getModalDelete']);
Route::get('jamaahs/{jamaahs}', ['as'=> 'jamaahs.show', 'uses' => 'JamaahController@show']);
Route::get('jamaahs/{jamaahs}/edit', ['as'=> 'jamaahs.edit', 'uses' => 'JamaahController@edit']);

});
